[package]
name = "ecs_dome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = {version = "0.16.1", features = ["specs-derive"] }
